# Лабораторна робота 1. NumPy

**Тема:** основи роботи з бібліотекою NumPy, масиви, вектори та матриці.

### Правила роботи
- Виконуйте завдання послідовно.
- Для обчислень використовуйте можливості **NumPy**.
- Не замінюйте операції NumPy звичайними Python-циклами, якщо це прямо не вказано в умові.
- Після виконання кожного завдання виводьте отриманий результат.


## 0. Підготовка середовища

### Завдання 0
Імпортуйте бібліотеку NumPy з псевдонімом `np`. Виведіть версію встановленої бібліотеки NumPy.

In [1]:
import numpy as np  # підключаємо NumPy під коротким іменем np

print("Версія NumPy:", np.__version__)

Версія NumPy: 2.1.3


## 1. Створення масивів NumPy

### Завдання 1
Створіть одновимірний NumPy-масив із чисел:
`[2, 4, 6, 8, 10]`.

Виведіть масив та його тип за допомогою `type()`.

In [2]:
arr = np.array([2, 4, 6, 8, 10])  # масив створюється зі звичайного списку

print("Масив:", arr)
print("Тип:", type(arr))  # numpy.ndarray — основний тип масивів NumPy

Масив: [ 2  4  6  8 10]
Тип: <class 'numpy.ndarray'>


### Завдання 2
Створіть:
1. масив із 10 нулів;
2. масив із 8 одиниць;
3. масив із 6 елементів, усі значення яких дорівнюють `7`.

Використайте відповідні функції NumPy.

In [3]:
zeros = np.zeros(10)    # 10 нулів (тип елементів — float64)
ones = np.ones(8)       # 8 одиниць
sevens = np.full(6, 7)  # 6 елементів, кожен дорівнює 7

print("10 нулів:", zeros)
print("8 одиниць:", ones)
print("6 сімок:", sevens)

10 нулів: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
8 одиниць: [1. 1. 1. 1. 1. 1. 1. 1.]
6 сімок: [7 7 7 7 7 7]


### Завдання 3
Створіть масив цілих чисел від `1` до `20` включно.

Після цього створіть окремий масив парних чисел від `2` до `20`.

In [4]:
numbers = np.arange(1, 21)   # кінець не включається, тому 21, щоб дійти до 20
evens = np.arange(2, 21, 2)  # третій аргумент — крок

print("Від 1 до 20:", numbers)
print("Парні від 2 до 20:", evens)

Від 1 до 20: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Парні від 2 до 20: [ 2  4  6  8 10 12 14 16 18 20]


### Завдання 4
За допомогою `np.linspace()` створіть масив із **11 рівновіддалених чисел** від `0` до `1` включно.

In [5]:
points = np.linspace(0, 1, 11)  # 11 точок, обидва кінці включені, крок 0.1

print(points)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Завдання 5
Створіть матрицю розміром `3 × 4`, заповнену числами від `1` до `12`.

Спочатку створіть одновимірний масив, а потім змініть його форму.

In [6]:
flat = np.arange(1, 13)      # спочатку одновимірний масив 1..12
matrix = flat.reshape(3, 4)  # reshape повертає масив нової форми: 3 рядки × 4 стовпці

print("Одновимірний масив:", flat)
print("Матриця 3×4:")
print(matrix)

Одновимірний масив: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Матриця 3×4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 2. Основні характеристики масивів

### Завдання 6
Для матриці, створеної у попередньому завданні, визначте та виведіть:
- кількість вимірів;
- форму;
- загальну кількість елементів;
- тип даних елементів.

Використайте атрибути `ndim`, `shape`, `size`, `dtype`.

In [7]:
# matrix — матриця 3×4 із попереднього завдання
print("Кількість вимірів (ndim):", matrix.ndim)
print("Форма (shape):", matrix.shape)
print("Кількість елементів (size):", matrix.size)
print("Тип даних (dtype):", matrix.dtype)

Кількість вимірів (ndim): 2
Форма (shape): (3, 4)
Кількість елементів (size): 12
Тип даних (dtype): int64


### Завдання 7
Створіть масив:
`[1.2, 3.5, 5.7, 7.9]`.

Перетворіть його елементи на цілі числа за допомогою `astype()` та виведіть новий масив.

In [8]:
floats = np.array([1.2, 3.5, 5.7, 7.9])
ints = floats.astype(int)  # astype відкидає дробову частину, а не округлює: 5.7 → 5

print("Початковий масив:", floats)
print("Після astype(int):", ints)

Початковий масив: [1.2 3.5 5.7 7.9]
Після astype(int): [1 3 5 7]


## 3. Індексація та зрізи

### Завдання 8
Створіть масив:
`[10, 20, 30, 40, 50, 60, 70, 80]`.

Виведіть:
1. перший елемент;
2. останній елемент;
3. елементи з індексами від `2` до `5` включно;
4. кожен другий елемент.

In [9]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print("Перший елемент:", arr[0])
print("Останній елемент:", arr[-1])             # індекс -1 означає останній елемент
print("Елементи з індексами від 2 до 5 включно:", arr[2:6])  # кінець зрізу не входить, тому 6
print("Кожен другий елемент:", arr[::2])        # крок зрізу 2

Перший елемент: 10
Останній елемент: 80
Елементи з індексами від 2 до 5 включно: [30 40 50 60]
Кожен другий елемент: [10 30 50 70]


### Завдання 9
Створіть матрицю:

```text
[[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]]
```

Виведіть:
1. елемент `7`;
2. другий рядок;
3. третій стовпець;
4. підматрицю з останніх двох рядків і перших двох стовпців.

In [10]:
M = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

print("Елемент 7:", M[1, 2])        # [рядок, стовпець], нумерація з 0
print("Другий рядок:", M[1])
print("Третій стовпець:", M[:, 2])  # «:» означає всі рядки
print("Останні два рядки, перші два стовпці:")
print(M[-2:, :2])

Елемент 7: 7
Другий рядок: [5 6 7 8]
Третій стовпець: [ 3  7 11]
Останні два рядки, перші два стовпці:
[[ 5  6]
 [ 9 10]]


### Завдання 10
Створіть масив чисел від `1` до `15`.

Замініть усі елементи з індексами від `5` до `9` включно на число `0`.

In [11]:
arr = np.arange(1, 16)  # числа від 1 до 15
print("До заміни:   ", arr)

arr[5:10] = 0  # індекси 5..9 включно; одне число присвоюється всьому зрізу
print("Після заміни:", arr)

До заміни:    [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Після заміни: [ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]


## 4. Арифметичні операції та агрегатні функції

### Завдання 11
Створіть два масиви:

```python
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
```

Виконайте поелементно:
- додавання;
- віднімання;
- множення;
- ділення.

In [12]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

# арифметичні оператори в NumPy діють поелементно, без циклів
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)
print("a / b =", a / b)  # оператор / завжди повертає тип float

a + b = [11 22 33 44 55]
a - b = [ -9 -18 -27 -36 -45]
a * b = [ 10  40  90 160 250]
a / b = [0.1 0.1 0.1 0.1 0.1]


### Завдання 12
Для масиву:

`[4, 8, 15, 16, 23, 42]`

обчисліть:
- суму;
- середнє значення;
- мінімум;
- максимум;
- медіану;
- стандартне відхилення.

In [13]:
data = np.array([4, 8, 15, 16, 23, 42])

print("Сума:", data.sum())
print("Середнє:", data.mean())
print("Мінімум:", data.min())
print("Максимум:", data.max())
print("Медіана:", np.median(data))  # методу .median() у масиву немає, тому np.median
print("Стандартне відхилення:", round(data.std(), 4))  # ddof=0: ділимо на n

Сума: 108
Середнє: 18.0
Мінімум: 4
Максимум: 42
Медіана: 15.5
Стандартне відхилення: 12.3153


### Завдання 13
Створіть матрицю:

```text
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

Обчисліть:
1. суму всіх елементів;
2. суму по кожному стовпцю;
3. суму по кожному рядку;
4. середнє значення по кожному стовпцю.

In [14]:
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Сума всіх елементів:", M.sum())
print("Сума по кожному стовпцю:", M.sum(axis=0))  # axis=0 — сумуємо вздовж стовпця (зверху вниз)
print("Сума по кожному рядку:", M.sum(axis=1))    # axis=1 — сумуємо вздовж рядка (зліва направо)
print("Середнє по кожному стовпцю:", M.mean(axis=0))

Сума всіх елементів: 45
Сума по кожному стовпцю: [12 15 18]
Сума по кожному рядку: [ 6 15 24]
Середнє по кожному стовпцю: [4. 5. 6.]


### Завдання 14
Для масиву чисел від `1` до `10` обчисліть:
- квадрат кожного елемента;
- квадратний корінь кожного елемента;
- натуральний логарифм кожного елемента.

Використайте функції NumPy.

In [15]:
x = np.arange(1, 11)

squares = np.square(x)
roots = np.sqrt(x)
logs = np.log(x)  # np.log — натуральний логарифм (основа e)

print("x:", x)
print("Квадрати:", squares)
print("Квадратні корені:", np.round(roots, 4))  # округлюємо лише для зручного виведення
print("Натуральні логарифми:", np.round(logs, 4))

x: [ 1  2  3  4  5  6  7  8  9 10]
Квадрати: [  1   4   9  16  25  36  49  64  81 100]
Квадратні корені: [1.     1.4142 1.7321 2.     2.2361 2.4495 2.6458 2.8284 3.     3.1623]
Натуральні логарифми: [0.     0.6931 1.0986 1.3863 1.6094 1.7918 1.9459 2.0794 2.1972 2.3026]


## 5. Логічні операції та фільтрація

### Завдання 15
Створіть масив:

`[3, 7, 12, 18, 21, 25, 30, 34]`

За допомогою булевої маски виведіть:
1. усі числа, більші за `15`;
2. усі парні числа;
3. числа в діапазоні від `10` до `30` включно.

In [16]:
arr = np.array([3, 7, 12, 18, 21, 25, 30, 34])

# порівняння дає масив True/False (маску), а arr[маска] лишає елементи, де True
print("Більші за 15:", arr[arr > 15])
print("Парні:", arr[arr % 2 == 0])
# для масивів умови поєднуються через &, а не and; кожна умова в дужках
print("Від 10 до 30 включно:", arr[(arr >= 10) & (arr <= 30)])

Більші за 15: [18 21 25 30 34]
Парні: [12 18 30 34]
Від 10 до 30 включно: [12 18 21 25 30]


### Завдання 16
Для масиву:

`[-5, 3, -2, 8, -1, 10, 0]`

замініть усі від’ємні значення на `0`.

Не використовуйте цикл `for`.

In [17]:
arr = np.array([-5, 3, -2, 8, -1, 10, 0])
print("До:   ", arr)

arr[arr < 0] = 0  # маска вибирає від'ємні елементи, присвоєння замінює їх на 0 без циклу
print("Після:", arr)

До:    [-5  3 -2  8 -1 10  0]
Після: [ 0  3  0  8  0 10  0]


### Завдання 17
Створіть масив випадкових цілих чисел від `0` до `100` розміром `20`.

Порахуйте:
- скільки елементів більші за `50`;
- скільки елементів менші або дорівнюють `50`.

Для відтворюваності встановіть `np.random.seed(42)`.

In [18]:
np.random.seed(42)                        # фіксуємо генератор, щоб числа щоразу були однакові
rnd = np.random.randint(0, 101, size=20)  # верхня межа не входить, тому 101, щоб включити 100

print("Масив:", rnd)
print("Кількість більших за 50:", np.sum(rnd > 50))  # True рахується як 1, тому sum дає кількість
print("Кількість менших або рівних 50:", np.sum(rnd <= 50))

Масив: [51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]
Кількість більших за 50: 12
Кількість менших або рівних 50: 8


## 6. Зміна форми та об'єднання масивів

### Завдання 18
Створіть масив чисел від `1` до `24`.

Перетворіть його:
1. у матрицю `4 × 6`;
2. у матрицю `6 × 4`;
3. у тривимірний масив форми `2 × 3 × 4`.

Після кожного перетворення виведіть `shape`.

In [19]:
arr = np.arange(1, 24 + 1)  # 24 елементи; добуток розмірів нової форми теж має бути 24

m_4x6 = arr.reshape(4, 6)
print(m_4x6)
print("shape:", m_4x6.shape)

m_6x4 = arr.reshape(6, 4)
print(m_6x4)
print("shape:", m_6x4.shape)

t_2x3x4 = arr.reshape(2, 3, 4)  # 2 блоки, у кожному матриця 3×4
print(t_2x3x4)
print("shape:", t_2x3x4.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
shape: (4, 6)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
shape: (6, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
shape: (2, 3, 4)


### Завдання 19
Створіть дві матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
```

Об’єднайте їх:
1. вертикально;
2. горизонтально.

Використайте функції NumPy.

In [20]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("Вертикально (np.vstack), B під A:")
print(np.vstack((A, B)))  # vstack ставить масиви один під одним (додаються рядки)
print("Горизонтально (np.hstack), B праворуч від A:")
print(np.hstack((A, B)))  # hstack ставить масиви поруч (додаються стовпці)

Вертикально (np.vstack), B під A:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Горизонтально (np.hstack), B праворуч від A:
[[1 2 5 6]
 [3 4 7 8]]


### Завдання 20
Створіть матрицю `3 × 4` із числами від `1` до `12`.

Перетворіть її назад в одновимірний масив двома способами:
- за допомогою `flatten()`;
- за допомогою `ravel()`.

Порівняйте результати.

In [21]:
M = np.arange(1, 13).reshape(3, 4)

f = M.flatten()  # завжди створює нову копію даних
r = M.ravel()    # якщо можливо, повертає представлення (view) тих самих даних, без копіювання

print("flatten():", f)
print("ravel():  ", r)
print("Значення однакові:", np.array_equal(f, r))
print("flatten має спільну пам'ять з M:", np.shares_memory(M, f))
print("ravel має спільну пам'ять з M:  ", np.shares_memory(M, r))

# наслідок: зміна r змінює і M, а зміна f на M не впливає
f[0] = 100
r[1] = 200
print("M після f[0] = 100 і r[1] = 200:")
print(M)

flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
ravel():   [ 1  2  3  4  5  6  7  8  9 10 11 12]
Значення однакові: True
flatten має спільну пам'ять з M: False
ravel має спільну пам'ять з M:   True
M після f[0] = 100 і r[1] = 200:
[[  1 200   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


## 7. Дії з векторами

### Завдання 21
Дано два вектори:

```text
a = [2, 4, 6]
b = [1, 3, 5]
```

Знайдіть:
- суму векторів;
- різницю векторів;
- результат множення кожного вектора на число `3`.

In [22]:
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print("a + b =", a + b)
print("a - b =", a - b)
print("3 · a =", 3 * a)  # число множиться на кожну координату
print("3 · b =", 3 * b)

a + b = [ 3  7 11]
a - b = [1 1 1]
3 · a = [ 6 12 18]
3 · b = [ 3  9 15]


### Завдання 22
Для векторів:

```text
a = [1, 2, 3]
b = [4, 5, 6]
```

Обчисліть їх **скалярний добуток** двома способами:
1. за допомогою `np.dot()`;
2. за допомогою оператора `@`.

In [23]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# скалярний добуток: 1·4 + 2·5 + 3·6 = 32
print("np.dot(a, b) =", np.dot(a, b))
print("a @ b =", a @ b)

np.dot(a, b) = 32
a @ b = 32


### Завдання 23
Для вектора:

```text
v = [3, 4]
```

обчисліть його евклідову норму.

Потім нормалізуйте вектор, тобто отримайте вектор одиничної довжини.

In [24]:
v = np.array([3, 4])

norm = np.linalg.norm(v)  # довжина вектора: √(3² + 4²) = 5
unit = v / norm           # ділимо кожну координату на довжину

print("Евклідова норма:", norm)
print("Нормалізований вектор:", unit)
print("Довжина нормалізованого вектора:", np.linalg.norm(unit))

Евклідова норма: 5.0
Нормалізований вектор: [0.6 0.8]
Довжина нормалізованого вектора: 1.0


### Завдання 24
Дано вектори:

```text
a = [1, 0, 0]
b = [0, 1, 0]
```

Знайдіть їх векторний добуток за допомогою `np.cross()`.

In [25]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

# векторний добуток перпендикулярний обом векторам; для осей x і y це вісь z
print("a × b =", np.cross(a, b))

a × b = [0 0 1]


### Завдання 25
Дано два вектори:

```text
a = [1, 2]
b = [2, 1]
```

Обчисліть косинус кута між ними за формулою через скалярний добуток і норми векторів.

Додатково знайдіть сам кут у градусах.

In [26]:
a = np.array([1, 2])
b = np.array([2, 1])

cos_angle = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))  # cos φ = (a·b) / (|a|·|b|)
angle = np.degrees(np.arccos(cos_angle))  # arccos повертає радіани, np.degrees переводить у градуси

print("Косинус кута:", round(cos_angle, 4))
print("Кут у градусах:", round(angle, 2))

Косинус кута: 0.8
Кут у градусах: 36.87


## 8. Дії з матрицями

### Завдання 26
Дано матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6]]
```

Знайдіть транспоновану матрицю двома способами:
1. за допомогою `.T`;
2. за допомогою `np.transpose()`.

In [27]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print("A.T:")
print(A.T)  # рядки стають стовпцями: форма (2, 3) → (3, 2)
print("np.transpose(A):")
print(np.transpose(A))
print("Результати однакові:", np.array_equal(A.T, np.transpose(A)))

A.T:
[[1 4]
 [2 5]
 [3 6]]
np.transpose(A):
[[1 4]
 [2 5]
 [3 6]]
Результати однакові: True


### Завдання 27
Дано матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[2, 0],
     [1, 2]]
```

Обчисліть:
1. поелементний добуток `A * B`;
2. матричний добуток `A @ B`.

Поясніть у коментарі до коду, чим відрізняються ці операції.

In [28]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[2, 0],
              [1, 2]])

print("A * B (поелементний добуток):")
print(A * B)
print("A @ B (матричний добуток):")
print(A @ B)

# Чим відрізняються:
# A * B множить елементи на однакових позиціях: результат[i, j] = A[i, j] * B[i, j].
# A @ B множить за правилом «рядок на стовпець»: результат[i, j] = сума A[i, k] * B[k, j],
#   тобто i-й рядок A скалярно множиться на j-й стовпець B.
# Тому результати різні. До того ж A @ B у загальному випадку не дорівнює B @ A.

A * B (поелементний добуток):
[[2 0]
 [3 8]]
A @ B (матричний добуток):
[[ 4  4]
 [10  8]]


### Завдання 28
Для матриці:

```text
A = [[4, 7],
     [2, 6]]
```

обчисліть:
- визначник;
- обернену матрицю.

Перевірте результат, помноживши початкову матрицю на обернену.

In [29]:
A = np.array([[4, 7],
              [2, 6]])

det = np.linalg.det(A)    # 4·6 − 7·2 = 10
A_inv = np.linalg.inv(A)  # обернена існує, бо визначник ≠ 0

print("Визначник:", round(det, 4))
print("Обернена матриця:")
print(A_inv)

check = A @ A_inv
print("Перевірка A @ A_inv:")
print(np.round(check, 10) + 0.0)  # прибираємо похибки float (~1e-16) і «-0.»
print("Вийшла одинична матриця:", np.allclose(check, np.eye(2)))

Визначник: 10.0
Обернена матриця:
[[ 0.6 -0.7]
 [-0.2  0.4]]
Перевірка A @ A_inv:
[[1. 0.]
 [0. 1.]]
Вийшла одинична матриця: True


### Завдання 29
Розв’яжіть систему лінійних рівнянь за допомогою NumPy:

```text
2x +  y = 5
 x + 3y = 6
```

Сформуйте матрицю коефіцієнтів `A` і вектор правих частин `b`.

Використайте `np.linalg.solve()`.

In [30]:
A = np.array([[2, 1],   # коефіцієнти при x та y з кожного рівняння
              [1, 3]])
b = np.array([5, 6])    # праві частини

solution = np.linalg.solve(A, b)  # розв'язує систему A · [x, y] = b

print("x =", round(solution[0], 4))
print("y =", round(solution[1], 4))
print("Перевірка: A @ [x, y] =", A @ solution, "| b =", b)

x = 1.8
y = 1.4
Перевірка: A @ [x, y] = [5. 6.] | b = [5 6]


### Завдання 30
Створіть одиничну матрицю розміром `4 × 4`.

Перевірте властивість одиничної матриці: помножте на неї довільну матрицю `4 × 4` та порівняйте результат з початковою матрицею.

In [31]:
I = np.eye(4, dtype=int)            # одинична матриця: 1 на головній діагоналі, решта 0
M = np.arange(1, 17).reshape(4, 4)  # довільна матриця 4×4

print("Одинична матриця I:")
print(I)
print("Матриця M:")
print(M)
print("M @ I:")
print(M @ I)
print("M @ I дорівнює M:", np.array_equal(M @ I, M))
print("I @ M дорівнює M:", np.array_equal(I @ M, M))

Одинична матриця I:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
Матриця M:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
M @ I:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
M @ I дорівнює M: True
I @ M дорівнює M: True


## 9. Broadcasting (операція трансляції)

### Завдання 31
Створіть матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

Додайте число `10` до кожного її елемента.

In [32]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(A + 10)  # broadcasting: число 10 додається до кожного елемента матриці

[[11 12 13]
 [14 15 16]
 [17 18 19]]


### Завдання 32
До матриці:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

додайте вектор:

```text
v = [10, 20, 30]
```

Проаналізуйте, як NumPy застосував broadcasting.

In [33]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
v = np.array([10, 20, 30])

result = A + v
print("Форма A:", A.shape, "| форма v:", v.shape)
print("A + v:")
print(result)

# Як спрацював broadcasting:
# NumPy порівнює форми справа наліво: (3, 3) і (3,). Останні розміри збігаються (3 = 3),
# тому v трактується як рядок форми (1, 3) і «повторюється» для кожного з 3 рядків A.
# У підсумку до кожного рядка додано [10, 20, 30]: перший стовпець +10, другий +20, третій +30.

Форма A: (3, 3) | форма v: (3,)
A + v:
[[11 22 33]
 [14 25 36]
 [17 28 39]]


### Завдання 33
Нормалізуйте **кожен стовпець** матриці:

```text
A = [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]]
```

за формулою:

\[
z = \frac{x - \mu}{\sigma}
\]

де `μ` — середнє значення стовпця, `σ` — стандартне відхилення стовпця.

Не використовуйте цикл `for`.

In [34]:
A = np.array([[10, 20, 30],
              [20, 30, 40],
              [30, 40, 50]])

mu = A.mean(axis=0)     # середнє кожного стовпця, форма (3,)
sigma = A.std(axis=0)   # стандартне відхилення кожного стовпця (ddof=0)
Z = (A - mu) / sigma    # broadcasting: mu і sigma застосовуються до кожного рядка, без циклу

print("Середні значення стовпців μ:", mu)
print("Стандартні відхилення стовпців σ:", np.round(sigma, 4))
print("Нормалізована матриця Z:")
print(np.round(Z, 4))
print("Перевірка — середні стовпців Z:", np.round(Z.mean(axis=0), 10))
print("Перевірка — σ стовпців Z:", np.round(Z.std(axis=0), 10))

Середні значення стовпців μ: [20. 30. 40.]
Стандартні відхилення стовпців σ: [8.165 8.165 8.165]
Нормалізована матриця Z:
[[-1.2247 -1.2247 -1.2247]
 [ 0.      0.      0.    ]
 [ 1.2247  1.2247  1.2247]]
Перевірка — середні стовпців Z: [0. 0. 0.]
Перевірка — σ стовпців Z: [1. 1. 1.]


## 10. Випадкові дані

### Завдання 34
Встановіть `np.random.seed(42)` та створіть:
1. 10 випадкових цілих чисел від `1` до `100`;
2. матрицю `3 × 3` випадкових чисел від `0` до `1`;
3. 1000 значень із нормального розподілу.

Для третього масиву обчисліть середнє та стандартне відхилення.

In [35]:
np.random.seed(42)

ints = np.random.randint(1, 101, size=10)   # цілі від 1 до 100 включно
uniform = np.random.rand(3, 3)              # дробові числа, рівномірно на [0, 1)
normal = np.random.normal(0, 1, size=1000)  # нормальний розподіл із середнім 0 і σ = 1

print("10 випадкових цілих:", ints)
print("Матриця 3×3 з [0, 1):")
print(np.round(uniform, 4))
# для нормального розподілу очікуємо середнє близько 0 і стандартне відхилення близько 1
print("Середнє:", round(normal.mean(), 4))
print("Стандартне відхилення:", round(normal.std(), 4))

10 випадкових цілих: [52 93 15 72 61 21 83 87 75 75]
Матриця 3×3 з [0, 1):
[[0.8662 0.6011 0.7081]
 [0.0206 0.9699 0.8324]
 [0.2123 0.1818 0.1834]]
Середнє: 0.0222
Стандартне відхилення: 0.9792


### Завдання 35
Змоделюйте оцінки 30 студентів — випадкові цілі числа від `0` до `100`.

Визначте:
- середню оцінку;
- медіану;
- найвищу та найнижчу оцінки;
- кількість студентів, які отримали не менше `60`;
- відсоток студентів, які отримали не менше `90`.

In [36]:
np.random.seed(42)  # для відтворюваності, як у попередніх завданнях
grades = np.random.randint(0, 101, size=30)  # оцінки від 0 до 100 включно

print("Оцінки:", grades)
print("Середня оцінка:", round(grades.mean(), 2))
print("Медіана:", np.median(grades))
print("Найвища:", grades.max(), "| найнижча:", grades.min())
print("Кількість студентів з оцінкою не менше 60:", np.sum(grades >= 60))
# середнє булевого масиву — це частка значень True
print("Відсоток студентів з оцінкою не менше 90:", round(np.mean(grades >= 90) * 100, 1), "%")

Оцінки: [51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37  1 63 59 20
 32 75 57 21 88 48]
Середня оцінка: 50.87
Медіана: 54.5
Найвища: 99 | найнижча: 1
Кількість студентів з оцінкою не менше 60: 13
Відсоток студентів з оцінкою не менше 90: 6.7 %


## 11. Підсумкові завдання

### Завдання 36
Дано результати продажів трьох товарів за чотири місяці:

```text
sales = [[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]]
```

Рядки — товари, стовпці — місяці.

Визначте:
1. загальний обсяг продажів кожного товару;
2. загальний обсяг продажів у кожному місяці;
3. товар із найбільшими сумарними продажами;
4. місяць із найбільшим загальним обсягом продажів;
5. середній обсяг продажів кожного товару.

In [37]:
sales = np.array([[120, 150, 170, 160],
                  [80, 90, 100, 110],
                  [200, 180, 210, 230]])  # рядки — товари, стовпці — місяці

product_totals = sales.sum(axis=1)  # сума по рядку → продажі кожного товару
month_totals = sales.sum(axis=0)    # сума по стовпцю → продажі за кожен місяць
best_product = np.argmax(product_totals)  # argmax повертає індекс найбільшого значення
best_month = np.argmax(month_totals)

print("Загальні продажі кожного товару:", product_totals)
print("Загальні продажі в кожному місяці:", month_totals)
# +1, бо індекси в NumPy починаються з 0
print(f"Товар із найбільшими продажами: №{best_product + 1} ({product_totals[best_product]})")
print(f"Місяць із найбільшими продажами: №{best_month + 1} ({month_totals[best_month]})")
print("Середні продажі кожного товару:", sales.mean(axis=1))

Загальні продажі кожного товару: [600 380 820]
Загальні продажі в кожному місяці: [400 420 480 500]
Товар із найбільшими продажами: №3 (820)
Місяць із найбільшими продажами: №4 (500)
Середні продажі кожного товару: [150.  95. 205.]


### Завдання 37
Створіть квадратну матрицю `5 × 5` із випадкових цілих чисел від `1` до `20`.

Виконайте:
1. знайдіть суму головної діагоналі;
2. знайдіть суму побічної діагоналі;
3. знайдіть максимальний елемент кожного рядка;
4. знайдіть мінімальний елемент кожного стовпця;
5. замініть усі елементи, менші за середнє значення всієї матриці, на `0`.

In [38]:
np.random.seed(42)
M = np.random.randint(1, 21, size=(5, 5))  # цілі від 1 до 20 включно
print("Матриця:")
print(M)

print("Сума головної діагоналі:", np.trace(M))  # trace — сума елементів M[i, i]
# fliplr розвертає порядок стовпців, тож побічна діагональ стає головною
print("Сума побічної діагоналі:", np.fliplr(M).diagonal().sum())
print("Максимум кожного рядка:", M.max(axis=1))
print("Мінімум кожного стовпця:", M.min(axis=0))

mean_all = M.mean()
M_new = M.copy()             # працюємо з копією, щоб оригінал не змінився
M_new[M_new < mean_all] = 0  # елементам, меншим за середнє, присвоюємо 0
print("Середнє всієї матриці:", mean_all)
print("Після заміни елементів, менших за середнє, на 0:")
print(M_new)

Матриця:
[[ 7 20 15 11  8]
 [ 7 19 11 11  4]
 [ 8  3  2 12  6]
 [ 2  1 12 12 17]
 [10 16 15 15 19]]
Сума головної діагоналі: 59
Сума побічної діагоналі: 32
Максимум кожного рядка: [20 19 12 17 19]
Мінімум кожного стовпця: [ 2  1  2 11  4]
Середнє всієї матриці: 10.52
Після заміни елементів, менших за середнє, на 0:
[[ 0 20 15 11  0]
 [ 0 19 11 11  0]
 [ 0  0  0 12  0]
 [ 0  0 12 12 17]
 [ 0 16 15 15 19]]


### Завдання 38
Дано матрицю ознак трьох об’єктів:

```text
X = [[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]]
```

Обчисліть **евклідову відстань** між:
- першим і другим рядком;
- першим і третім рядком;
- другим і третім рядком.

Використайте операції NumPy та `np.linalg.norm()`.

In [39]:
X = np.array([[2, 4, 6],
              [1, 3, 5],
              [5, 7, 9]])  # кожен рядок — окремий об'єкт

# евклідова відстань = норма різниці двох векторів
d_12 = np.linalg.norm(X[0] - X[1])
d_13 = np.linalg.norm(X[0] - X[2])
d_23 = np.linalg.norm(X[1] - X[2])

print("Відстань між 1-м і 2-м рядком:", round(d_12, 4))
print("Відстань між 1-м і 3-м рядком:", round(d_13, 4))
print("Відстань між 2-м і 3-м рядком:", round(d_23, 4))

Відстань між 1-м і 2-м рядком: 1.7321
Відстань між 1-м і 3-м рядком: 5.1962
Відстань між 2-м і 3-м рядком: 6.9282


### Завдання 39
Створіть матрицю `4 × 4` із довільних цілих чисел.

Для кожного рядка знайдіть його норму та створіть нову матрицю, у якій кожен рядок нормалізований до одиничної довжини.

Спробуйте виконати завдання без циклів.

In [40]:
np.random.seed(42)
M = np.random.randint(1, 10, size=(4, 4))  # довільні цілі від 1 до 9, тож нульових рядків не буде

# норма кожного рядка; keepdims=True дає форму (4, 1) замість (4,), тому ділення йде по рядках
norms = np.linalg.norm(M, axis=1, keepdims=True)
M_unit = M / norms  # broadcasting: кожен рядок ділиться на свою норму, без циклу

print("Матриця:")
print(M)
print("Норми рядків:", np.round(norms.ravel(), 4))
print("Нормалізована матриця:")
print(np.round(M_unit, 4))
print("Перевірка — норми нових рядків:", np.round(np.linalg.norm(M_unit, axis=1), 10))

Матриця:
[[7 4 8 5]
 [7 3 7 8]
 [5 4 8 8]
 [3 6 5 2]]
Норми рядків: [12.4097 13.0767 13.      8.6023]
Нормалізована матриця:
[[0.5641 0.3223 0.6447 0.4029]
 [0.5353 0.2294 0.5353 0.6118]
 [0.3846 0.3077 0.6154 0.6154]
 [0.3487 0.6975 0.5812 0.2325]]
Перевірка — норми нових рядків: [1. 1. 1. 1.]


### Завдання 40
Створіть матрицю коефіцієнтів і вектор правих частин для системи:

```text
 x + 2y +  z =  9
2x +  y -  z =  8
3x -  y + 2z =  3
```

1. Розв’яжіть систему за допомогою `np.linalg.solve()`.
2. Перевірте знайдений розв’язок матричним множенням `A @ x`.
3. Порівняйте результат із вектором `b`.

In [41]:
A = np.array([[1, 2, 1],
              [2, 1, -1],
              [3, -1, 2]])  # коефіцієнти при x, y, z
b = np.array([9, 8, 3])     # праві частини

print("Матриця коефіцієнтів A:")
print(A)
print("Вектор правих частин b:", b)

x = np.linalg.solve(A, b)
print("Розв'язок [x, y, z]:", x)

check = A @ x
print("A @ x =", check)
print("b     =", b)
print("A @ x збігається з b:", np.allclose(check, b))  # allclose допускає похибку float

Матриця коефіцієнтів A:
[[ 1  2  1]
 [ 2  1 -1]
 [ 3 -1  2]]
Вектор правих частин b: [9 8 3]
Розв'язок [x, y, z]: [ 2.22222222  3.44444444 -0.11111111]
A @ x = [9. 8. 3.]
b     = [9 8 3]
A @ x збігається з b: True


---

## Самоперевірка

Після виконання роботи студент повинен уміти:
- створювати та перетворювати NumPy-масиви;
- використовувати індексацію та зрізи;
- виконувати векторизовані арифметичні операції;
- застосовувати агрегатні функції;
- використовувати булеві маски;
- змінювати форму та об'єднувати масиви;
- виконувати основні дії з векторами;
- виконувати основні операції з матрицями;
- застосовувати broadcasting;
- використовувати функції `numpy.linalg` для задач лінійної алгебри.
